// Generated by https://quicktype.io

export class ProductDetails {
    name:        string;
    price:       any;
    category:    string;
    description: string;
    image?:      string;
    quantity?:   number = 1;
}
